### ISSUE TITLE
flutter version

### ISSUE THREAD

**Issue by erickluz** [sopheamen007/app.mobile.tiktok-app-ui#3]
The current Flutter version doesn't work correctly with the libraries from the project. I have downgrade to version 1.20.2 to work correctly.
I suggest defining the Flutter version in the "pubspec.yaml" file.

Something like this:

```
dependencies:
  flutter:
    sdk: flutter
    version: 1.20.2
```

I suggest too, to test the last version from the Flutter that's works fine.
